### ISSUE TITLE
Getting renee ready for Travel

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/pg-it#12]

**Comment by PeaceGeeks** [comment]
hardware is in good share
i can train partners on tools and basic digi security practices

**Comment by improvethings** [comment]
Renee is travelling, so this can be closed?

**Comment by PeaceGeeks** [comment]
Yes




*Renee Black*,
*Executive Director*
#210 - 128 West Hastings Street
Vancouver, BC, V6B 1G8
*p.* 778-235-7458 | *e.* renee@peacegeeks.org
*skype.* reneeontheroad
