### ISSUE TITLE
Digital Security Training Day

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/pg-it#2]

**Comment by PeaceGeeks** [comment]
Operational security (how you're operating while in field)
- Hardware security (what happens if computer, phone is stolen)
- Best Practices (USB keys, lock screen with 30 seconds or shut lid, passwords, covering cameras, travel/ airport security, wiping devices before travel, choosing tools (OrBot, K-9 Mail, Mailvelope on mobile, OwnCloud App), setting up an encrypted partition (assuming devices are compromised)
- Servers
- Questions we should always be asking ourselves
 
Infrastructure
- Martus
- Secure Email Management
- OwnCloud (cost support time) - they can't add users at this time, but otherwise, our server works; need to make sure there is never a certificate change; if there is ever a prompt, they should contact us
- Jitsi (cost support time) - they can't add users at this time, but otherwise, our server works; need to understand accepting certificates
- RocketChat (group management)

**Comment by PeaceGeeks** [comment]
Store private key in Keepass

**Comment by improvethings** [comment]
This was completed.
